export const popularSearch = [
  {
    title: "Popular New Cars for sale",
    content: [
      "2025 Chevrolet Silverado 1500 for sale",
      "2025 Ford F-150 for sale",
      "2025 Ford Mustang for sale",
      "2025 Ford Ranger for sale",
      "2025 GMC Sierra 1500 for sale",
      "2025 Honda CR-V for sale",
      "2025 Jeep Grand Cherokee for sale",
      "2025 Jeep Wrangler for sale",
      "2025 RAM 1500 for sale",
      "2025 Toyota Camry for sale",
      "2025 Toyota Sequoia for sale",
      "2025 Toyota Tacoma for sale",
    ],
  },
  {
    title: "Popular Used Cars for sale",
    content: [
      "Used Dodge Challenger for sale",
      "Used Dodge Charger for sale",
      "Used Ford Explorer for sale",
      "Used Ford F-150 for sale",
      "Used Honda Accord for sale",
      "Used Honda Civic for sale",
      "Used Jeep Grand Cherokee for sale",
      "Used Jeep Wrangler for sale",
      "Used Nissan Rogue for sale",
      "Used RAM 1500 for sale",
      "Used Toyota Camry for sale",
      "Used Toyota Tacoma for sale",
    ],
  },
  {
    title: "Research Popular New Cars for sale",
    content: [
      "2025 Chevrolet Silverado 1500 for sale",
      "2025 Ford F-150 for sale",
      "2025 Ford Mustang for sale",
      "2025 Ford Ranger for sale",
      "2025 GMC Sierra 1500 for sale",
      "2025 Honda CR-V for sale",
      "2025 Jeep Grand Cherokee for sale",
      "2025 Jeep Wrangler for sale",
      "2025 RAM 1500 for sale",
      "2025 Toyota Camry for sale",
      "2025 Toyota Sequoia for sale",
      "2025 Toyota Tacoma for sale",
    ],
  },
  {
    title: "Research Popular Used Cars for sale",
    content: [
      "Used Dodge Challenger for sale",
      "Used Dodge Charger for sale",
      "Used Ford Explorer for sale",
      "Used Ford F-150 for sale",
      "Used Honda Accord for sale",
      "Used Honda Civic for sale",
      "Used Jeep Grand Cherokee for sale",
      "Used Jeep Wrangler for sale",
      "Used Nissan Rogue for sale",
      "Used RAM 1500 for sale",
      "Used Toyota Camry for sale",
      "Used Toyota Tacoma for sale",
    ],
  },
];
